spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect # (optional) specify the Hibernate dialect for PostgreSQL

Application:
  jwt:
    secret-key: 2731a660061e5a77b1a4931282d6390fedd0a85cec135ad59e1e8f374fa3f726
    expired-date: 900

Typesense:
  api-key: VQh8ZACqxR4DLfyUTWdgFKOg8FlPza3b
#  api-key from sokpheng